---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  
- name: Add user to group
  ansible.builtin.user:
    user: "{{user}}"
    group: root
    state: present

- name: Remove default nginx conf
  ansible.builtin.file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx conf
  ansible.builtin.copy:
    src: static-site-config
    dest: /etc/nginx/sites-available
    owner: "{{user}}"
    group: root
    mode: '0644'

- name: Enable website conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/static-site-config
    dest: /etc/nginx/sites-enabled/static-site-config
    state: link

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true


  