---
- name: Anstall apache and server static content
  hosts: all
  remote_user: kali
  become: true
  tasks: 
    - name: Install apache
      ansible.builtin.apt: 
        name: apache2
        state: present

    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Copy index file
      ansible.builtin.copy: 
        src: index.html
        dest: /var/www/html
        owner: kali
        group: kali
        mode: '0644'
        creates: /var/www/html/index.html